// <auto-generated />
using System;
using ERPApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPApi.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(452),
                            Description = "System Administrator",
                            IsSystemRole = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3100a53a-8f03-48ac-887d-4fe91ae2ca2a",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(590),
                            Description = "Regular User",
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("ERPApi.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ERPApi.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3452),
                            Icon = "dashboard",
                            IsActive = true,
                            Order = 1,
                            Title = "Dashboard",
                            Url = "/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3545),
                            Icon = "admin_panel_settings",
                            IsActive = true,
                            Order = 2,
                            Title = "Administration",
                            Url = "#"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3624),
                            Icon = "people",
                            IsActive = true,
                            Order = 1,
                            ParentId = 2,
                            Title = "Users",
                            Url = "/admin/users"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3626),
                            Icon = "assignment_ind",
                            IsActive = true,
                            Order = 2,
                            ParentId = 2,
                            Title = "Roles",
                            Url = "/admin/roles"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3628),
                            Icon = "security",
                            IsActive = true,
                            Order = 3,
                            ParentId = 2,
                            Title = "Permissions",
                            Url = "/admin/permissions"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3631),
                            Icon = "menu",
                            IsActive = true,
                            Order = 4,
                            ParentId = 2,
                            Title = "Menus",
                            Url = "/admin/menus"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3633),
                            Icon = "history",
                            IsActive = true,
                            Order = 5,
                            ParentId = 2,
                            Title = "Audit Logs",
                            Url = "/admin/audit-logs"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3635),
                            Icon = "person",
                            IsActive = true,
                            Order = 3,
                            Title = "Profile",
                            Url = "/profile"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 753, DateTimeKind.Utc).AddTicks(3636),
                            Icon = "settings",
                            IsActive = true,
                            Order = 4,
                            Title = "Settings",
                            Url = "/settings"
                        });
                });

            modelBuilder.Entity("ERPApi.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "users.view",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5252),
                            Description = "Can view users",
                            Group = "Users",
                            Name = "View Users"
                        },
                        new
                        {
                            Id = 2,
                            Code = "users.create",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5822),
                            Description = "Can create users",
                            Group = "Users",
                            Name = "Create Users"
                        },
                        new
                        {
                            Id = 3,
                            Code = "users.edit",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5824),
                            Description = "Can edit users",
                            Group = "Users",
                            Name = "Edit Users"
                        },
                        new
                        {
                            Id = 4,
                            Code = "users.delete",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5825),
                            Description = "Can delete users",
                            Group = "Users",
                            Name = "Delete Users"
                        },
                        new
                        {
                            Id = 5,
                            Code = "roles.view",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5826),
                            Description = "Can view roles",
                            Group = "Roles",
                            Name = "View Roles"
                        },
                        new
                        {
                            Id = 6,
                            Code = "roles.create",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5830),
                            Description = "Can create roles",
                            Group = "Roles",
                            Name = "Create Roles"
                        },
                        new
                        {
                            Id = 7,
                            Code = "roles.edit",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5831),
                            Description = "Can edit roles",
                            Group = "Roles",
                            Name = "Edit Roles"
                        },
                        new
                        {
                            Id = 8,
                            Code = "roles.delete",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5832),
                            Description = "Can delete roles",
                            Group = "Roles",
                            Name = "Delete Roles"
                        },
                        new
                        {
                            Id = 9,
                            Code = "permissions.view",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5833),
                            Description = "Can view permissions",
                            Group = "Permissions",
                            Name = "View Permissions"
                        },
                        new
                        {
                            Id = 10,
                            Code = "permissions.manage",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5835),
                            Description = "Can manage permissions",
                            Group = "Permissions",
                            Name = "Manage Permissions"
                        },
                        new
                        {
                            Id = 11,
                            Code = "menus.view",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5836),
                            Description = "Can view menus",
                            Group = "Menus",
                            Name = "View Menus"
                        },
                        new
                        {
                            Id = 12,
                            Code = "menus.manage",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5837),
                            Description = "Can manage menus",
                            Group = "Menus",
                            Name = "Manage Menus"
                        },
                        new
                        {
                            Id = 13,
                            Code = "audit.view",
                            CreatedDate = new DateTime(2026, 1, 21, 7, 48, 52, 752, DateTimeKind.Utc).AddTicks(5838),
                            Description = "Can view audit logs",
                            Group = "Audit",
                            Name = "View Audit Logs"
                        });
                });

            modelBuilder.Entity("ERPApi.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.RoleMenu", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 1
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 2
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 3
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 4
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 5
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 6
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 7
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 8
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            MenuId = 9
                        });
                });

            modelBuilder.Entity("ERPApi.Core.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = "59e429e4-ddd3-49ed-b397-9fff4d13f4f8",
                            PermissionId = 13
                        });
                });

            modelBuilder.Entity("ERPApi.Core.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ERPApi.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.ApplicationUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.Menu", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.RoleMenu", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApi.Core.Entities.ApplicationRole", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApi.Core.Entities.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.UserRole", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApi.Core.Entities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ERPApi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPApi.Core.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("ERPApi.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
